export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const INCREASE_QUANTITY_ITEM_CART = "INCREASE_QUANTITY_ITEM_CART";
export const DECREASE_QUANTITY_ITEM_CART = "DECREASE_QUANTITY_ITEM_CART";
export const RESET_QUANTITY_ITEM_CART = "RESET_QUANTITY_ITEM_CART";
